repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: debug-statements
        language_version: python3
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: pretty-format-json
        args: [ --autofix ]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
      - id: python-no-eval
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.4.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args: [ --py37-plus ]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake
        name: autoflake
        args: [ "--in-place", "--remove-unused-variables", "--remove-all-unused-imports" ]
        language: python
        files: \.py$
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        args: [ "--max-line-length=120" ]
